name: NER Sentinel CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:

  mobile-ci:
    name: Mobile Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build Android app
        run: ./gradlew build